---
- name: Install packages
  apt:
    name: "{{ prometheus_node_exporter_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
  - install

- name: Configure env file
  template:
    src: prometheus-node-exporter.j2
    dest: "{{ prometheus_node_exporter_env_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-node-exporter
  tags:
  - configure

- name: enable and start service
  service:
    name: "{{ prometheus_node_exporter_service_name }}"
    state: started
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
  - configure
